version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - es_log_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elk


  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  log_pilot:
    depends_on:
      - kibana
    image: registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/:/host"
    environment:
      FLUENTD_OUTPUT: elasticsearch
      
      # use your local machine ip
      ELASTICSEARCH_HOST: 192.168.221.24
      ELASTICSEARCH_PORT: 9200
    privileged: true
    networks:
      - elk


networks:

  elk:
    driver: bridge

volumes:
  es_log_data:
    external:
      name: es_log_data
